-- Layer Rules
hl.layer_rule({ name = "rofi-blur",          match = { namespace = "rofi" },                        blur = true })
hl.layer_rule({ name = "swaync-center-blur", match = { namespace = "swaync-control-center" },       blur = true })
hl.layer_rule({ name = "swaync-notif-blur",  match = { namespace = "swaync-notification-window" },  blur = true })

-- Window Rules: Layout / Tags
hl.window_rule({ name = "tile-godot",       match = { title = "(.*)(Godot)(.*)$" },                      tile = true })
hl.window_rule({ name = "content-games",    match = { tag = "games" },                                   content = "game" })
hl.window_rule({ name = "tag-from-content", match = { content = "game" },                                tag = "+games" })
hl.window_rule({ name = "tag-steam-apps",   match = { class = "^(steam_app.*|steam_app_%d+)$" },         tag = "+games" })
hl.window_rule({ name = "tag-gamescope",    match = { class = "^(gamescope)$" },                         tag = "+games" })
hl.window_rule({ name = "tag-waydroid",     match = { class = "(Waydroid)" },                            tag = "+games" })
hl.window_rule({ name = "tag-osu",          match = { class = "(osu!)" },                                tag = "+games" })

-- Window Rules: Opacity
hl.window_rule({ name = "opacity-terminals",        match = { class = "^(kitty|alacritty|Alacritty|org.wezfurlong.wezterm)$" }, opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-gcr-prompter",     match = { class = "^(gcr-prompter)$" },                                     opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-hyprpolkit-title", match = { title = "^(Hyprland Polkit Agent)$" },                            opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-firefox",          match = { class = "^(firefox)$" },                                          opacity = "1.00 1.00" })
hl.window_rule({ name = "opacity-brave",            match = { class = "^(Brave-browser)$" },                                    opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-thunar",           match = { class = "^(thunar)$" },                                           opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-steam",            match = { class = "^(Steam|steam|steamwebhelper)$" },                       opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-spotify-class",    match = { class = "^(Spotify)$" },                                          opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-spotify-title",    match = { title = "(.*)(Spotify)(.*)$" },                                   opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-vscodium",         match = { class = "^(VSCodium)$" },                                         opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-codium-url",       match = { class = "^(codium-url-handler)$" },                               opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-code",             match = { class = "^(code)$" },                                             opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-code-url",         match = { class = "^(code-url-handler)$" },                                 opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-termfm",           match = { class = "^(terminalFileManager)$" },                              opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-dolphin",          match = { class = "^(org.kde.dolphin)$" },                                  opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-ark",              match = { class = "^(org.kde.ark)$" },                                      opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-nwg-look",         match = { class = "^(nwg-look)$" },                                         opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-qt5ct",            match = { class = "^(qt5ct)$" },                                            opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-qt6ct",            match = { class = "^(qt6ct)$" },                                            opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-yad",              match = { class = "^(yad)$" },                                              opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-clapper",          match = { class = "^(com.github.rafostar.Clapper)$" },                      opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-flatseal",         match = { class = "^(com.github.tchx84.Flatseal)$" },                       opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-cartridges",       match = { class = "^(hu.kramo.Cartridges)$" },                              opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-obs",              match = { class = "^(com.obsproject.Studio)$" },                            opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-gnome-boxes",      match = { class = "^(gnome-boxes)$" },                                      opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-discord",          match = { class = "^(discord)$" },                                          opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-webcord",          match = { class = "^(WebCord)$" },                                          opacity = "0.90 0.90" })
hl.window_rule({ name = "opacity-warp",             match = { class = "^(app.drey.Warp)$" },                                    opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-protonup",         match = { class = "^(net.davidotek.pupgui2)$" },                            opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-signal",           match = { class = "^(Signal)$" },                                           opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-upscaler",         match = { class = "^(io.gitlab.theevilskeleton.Upscaler)$" },               opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-obsidian",         match = { class = "^(obsidian)$" },                                         opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-zotero",           match = { class = "^(Zotero)$" },                                           opacity = "0.80 0.80" })
hl.window_rule({ name = "opacity-pavucontrol",      match = { class = "^(pavucontrol)$" },                                      opacity = "0.80 0.70" })
hl.window_rule({ name = "opacity-pulseaudio",       match = { class = "^(org.pulseaudio.pavucontrol)$" },                       opacity = "0.80 0.70" })
hl.window_rule({ name = "opacity-blueman",          match = { class = "^(blueman-manager|.blueman-manager-wrapped)$" },         opacity = "0.80 0.70" })
hl.window_rule({ name = "opacity-nm",               match = { class = "^(nm-applet|nm-connection-editor)$" },                   opacity = "0.80 0.70" })
hl.window_rule({ name = "opacity-polkit-kde",       match = { class = "^(org.kde.polkit-kde-authentication-agent-1)$" },        opacity = "0.80 0.70" })

-- Window Rules: Float
hl.window_rule({ name = "float-qt5ct",       match = { class = "^(qt5ct)$" },                                     float = true })
hl.window_rule({ name = "float-nwg-look",    match = { class = "^(nwg-look)$" },                                  float = true })
hl.window_rule({ name = "float-ark",         match = { class = "^(org.kde.ark)$" },                               float = true })
hl.window_rule({ name = "float-signal",      match = { class = "^(Signal)$" },                                    float = true })
hl.window_rule({ name = "float-clapper",     match = { class = "^(com.github.rafostar.Clapper)$" },               float = true })
hl.window_rule({ name = "float-warp",        match = { class = "^(app.drey.Warp)$" },                             float = true })
hl.window_rule({ name = "float-protonup",    match = { class = "^(net.davidotek.pupgui2)$" },                     float = true })
hl.window_rule({ name = "float-eog",         match = { class = "^(eog)$" },                                       float = true })
hl.window_rule({ name = "float-upscaler",    match = { class = "^(io.gitlab.theevilskeleton.Upscaler)$" },        float = true })
hl.window_rule({ name = "float-yad",         match = { class = "^(yad)$" },                                       float = true })
hl.window_rule({ name = "float-pavucontrol", match = { class = "^(pavucontrol)$" },                               float = true })
hl.window_rule({ name = "float-blueman",     match = { class = "^(blueman-manager|.blueman-manager-wrapped)$" },  float = true })
hl.window_rule({ name = "float-nm",          match = { class = "^(nm-applet|nm-connection-editor)$" },            float = true })
hl.window_rule({ name = "float-polkit",      match = { class = "^(org.kde.polkit-kde-authentication-agent-1)$" }, float = true })
